### ISSUE TITLE
Висоти

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#1]
Привіт! 

В тебе на ".header-content-wrapper" і на ".form-wrapper" є конкретні висоти у пікселях. Ти впевнений, що вони там потрібні? Зазвичай по висоті контент має виштовухвати усілякі wrappers.

**Comment by Andrukas8** [comment]
фіксовані висоти видалив. Я їх був поставив тимчасово - щоб подивитись як виглядатимуть компоненти, а потім не прибрав. Ще в цьому ж комміті виправив опечатку в тегі title.
