### ISSUE TITLE
Правильна "роздача" шрифтів

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#10]
В тебе є

```
header .header-content-wrapper .header-data-wrapper .offer-wrapper .offer-item {
....
  font-family: "GothamProBold", "Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", Tahoma, sans-serif;
}
```

Тобто візуально воно виглядатиме жирним шрифтом, а "де юро" воно спеціфікується як font-weight: normal.

Ти хочеш зробити так наступна формула працювала:

- придумай правильні директиви @font-face
- потім впиши body { font-family: GothamPro, ... }
- і тоді, коли тобі потрібен шрифт "GothamProBold", то ти маєш просто вписати some-selector {font-weight: bold;} і уся ця хєрня має автоматично спрацювати і розпізнати, що для жирного варіанту GothamPro треба використовувати файл GothamProBold

Мені вдалось пояснити задачу?

**Comment by Andrukas8** [comment]
чи правильно я зрозумів:
коли потрібен жирний шрифт GothamPro, то замість GothamProBold з font-weight: normal краще використати GothamPro з font-weight: bold?
В цьому разі мі теж можемо видалити GothamProBold з папки шрифтів і зекономити 105 клобайтів?

**Comment by bucefal91** [comment]
Нєт :)

Тут трохи інший задум. По-перше, коли шось написано нормальним шрифтом, то воно має рендиритись через GothamProMedium. А якщо щось написано жирним шрифтом, то воно має рендеритись через GothamProBold. Тому зекомноминити не вийде. Тобі обидва файли шрифтів необхідні.

Я від требе прошу більш правильну сематичність твого кода. Зазвичай кожен шрифт можна використовувати у 4 базових варіаціях:

1. нормальний
2. жирний
3. курсивний
4. жирний і курсивний одночасно

Варіацій є значно більше, але це найпопулярніші. Тому сематично усе це має виглядати так: є шрифт (font-family, і є його параметри font-weight, font-style). Як ти реалізуєш ці 4 варіації зі звичайними (вбудованими) шрифтами? - дуже просто:

1. нормальний: font-family: "Arial";
2. жирний: font-family: Arial; font-weight: bold;
3. курсив: font-family: Arial; font-style: italic;
4. жирний і курсив: font-family: Arial; font-weight: bold; font-style: italic;

Тобто ти літерально пишеш браузеру "напиши мені цей текст у такому шрифті у такій варіації". І це правильно.

А як ти це зараз зробив з кастомними шрифтами? Ти зробив інашке:

1. нормальний: font-family: "GothamProMedium";
2. жирний: font-family: "GothamProBold";
3. (інших варіацій у тебе в дизайні, здається, нема)

Бачиш різницю? Тут ти семантично повідомляєш наступне браузеру: "напиши мені цей текст у шрифті GothamProBold і нормальній варіації", коли правильний варіант (по аналогу з прикладом з вбудованими шрифтами) мав би бути "напиши мені цей текст у шрифті GothamProMedium у жирній варіації.

Бачиш різницю на рівні семантики? В 1му випадку це один і той самий font-family у різних варіаціях, а у 2му випадку це 2 різні font-family і обидва у нормальних варіаціях.

І якщо дуже хочеться зекономити ~105 кілобайтів, то я би викинув з твого ЦССу декларацію GothamProRegular, бо принаймі зараз здається, що ти цей шрифт ніде не використовуєш.

**Comment by bucefal91** [comment]
У цього тікета високий приорітет. Я завтра забутаюсь у windows і як треба продивлюсь шрифти у photoshop'і. А то я не знаю, чи це мій лінукс не так PSD читає, чи то справді шрифти на вебсайті не такі, як у psd.

**Comment by bucefal91** [comment]
все було правильно зі шрифтами, просто браузер за змовчуванням дає певний font-weight для заголовків і нам ця жирність портила усю картину. Я тобі атачу тут патч. Я в ньому 2 області трохи переробив. Я їх переробив щоби вони відповідали точніше до вигляду PSD. На цих 2 областях я впевнився що шрифти у нормі. І я тобі атачу прінтскрін де я показую які це 2 області.
![untitled-1](https://cloud.githubusercontent.com/assets/17630965/22850320/1fd983ba-efcd-11e6-8257-8d73d1068c1f.png)
[alex.patch.txt](https://github.com/Andrukas8/responsive_design_practice/files/768167/alex.patch.txt)

**Comment by bucefal91** [comment]
Закриваю тікет як неактуальний.
