### ISSUE TITLE
СSS border: none;

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#11]
Чесно, я зараз погано пригадую, але принаймі раніше з border: none були деякі проблеми у IE браузері. Я зазвичай використовую border: 0.

Якщо в тебе буде час, то перевірь чи в усіх сучаних браузерах підтримується border: none;

**Comment by Andrukas8** [comment]
перевірив - наче працює, але всеодно виправив, на випадок старого браузера

**Comment by bucefal91** [comment]
так, я також зараз трохи пошукав в інеті і інет каже, що можна)
