### ISSUE TITLE
Erroneous website width

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#12]
Привіт!

Я би на цьому дизайні не робив би ширини. В мене екран трохи більше, ніж твій і дивись, сіра полоса не тянеться на усю ширину через .website-width І там нижче так само синьо-бірюзова полоса не тягнеться.
![screenshot from 2016-12-22 20-35-12](https://cloud.githubusercontent.com/assets/17630965/21445976/4cd5fe3e-c886-11e6-9be8-e6d4528f163a.png)

**Comment by Andrukas8** [comment]
начебто зробив, але мав клопіт з тим щоб правильно вирівняти той розділ в якому bell-curve, тому використав position: absolute для текста, який знаходиться над кривою.

**Comment by bucefal91** [comment]
Ти зробив добре, лише одне питання: а тобі взагалі ще потрібен клас .website-width? У хтмл він лише на <body> висить. А у ЦСС для різних media query він виглядає дуже схоже:

```
  .website-width {
    max-width: [whatever the media query max width says] px;
    width: 100%;
    margin-left: auto;
    margin-right: auto;
  }
```

Якщо я правильно розумію твій код, то цей клас тобі не потрібен.

**Comment by bucefal91** [comment]
В тебе ще один баг з"явився, який має бути пов"язаним з цим тікетом. Подивись на прінтскрін вище у цьому тікеті - в тебе лого і телефон добре стояли прямо на границі де закінчується блакитний фоновий малюнок.

А тепер лого і телефон виходять за границі фонового малюнка і виглядає некрасиво. Атачу скрін.
![screenshot from 2017-02-08 23-20-21](https://cloud.githubusercontent.com/assets/17630965/22770346/6629ac1a-ee55-11e6-9c4c-c62cfa2a977e.png)

**Comment by bucefal91** [comment]
Закриваю тікет як неактуальний.
