### ISSUE TITLE
Хедер .header-content-wrapper

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#13]
Я бачу, що ти попотів над .header-content-wrapper і його дітьми. Мабудь, це сама складна частина дизайну.

Але в тебе ще є багато розбіжностей з дизайном у цій частині
Дівиця принаймі у моєму лінуксі не знаходиться у правильному місці
середня колонка за висотою трохи менше ніж у дизайні
в самому низу між .header-content-wrapper і .about-company-wrapper є біла полоса десь 10 пікселів по висоті.

Я розумію, що це складний макет, тому можна ще попрацювати над ним, або якщо хочеш - я заверстаю цю частину і ти побачиш, як я рішив усі ці проблеми з якими, я впевнений, ти вже зіштовхнувся і спробував їх вирішити.

Мені здається, що краще 2й варіант - заверстати цю частину мені, щоб ти міг побачити і порівняти твоє і моє рішення.

**Comment by Andrukas8** [comment]
Згоден з тобою, давай підемо шяхом другого варіанту. Найголовніше, стосовно чого виникає багато питань щодо хедера - це тьотя (поведінка якої є непередбачувана), і розашування сірої форми "Давайте Начнем".

**Comment by bucefal91** [comment]
Закриваю тікет як неактуальний.
