### ISSUE TITLE
Маржин auto без ширини

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#14]
Якщо я правильно зрозумів твою логіку, то у body section .about-company-wrapper писати margin:0 auto нема сенсу, адже в тебе ширини фіксованої нема, тому цей дів буде 100% ширини і на маржу не буде місця.

**Comment by Andrukas8** [comment]
зробив. так, справді той марджін був зайвий

**Comment by bucefal91** [comment]
чудово!
