### ISSUE TITLE
Сіра полоска

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#16]
Порівняй з дизайном body section .about-company-wrapper .how-it-works-wrapper .how-it-works

В тебе знизу нема padding і воно виглядає дуже куцим. А в дизайні є простір між кінцем сірої полоски і там, де закінчується контент всередині body section .about-company-wrapper .how-it-works-wrapper .how-it-works тега

Порівняй трохи пильніше твоє рішення проти дизайна. Ще в тебе в параграфі line-height явно не такий, як у дизайні. Шрифт виглядає іншим,порівняно з дизайном (жирніший).
Відступи горизонтальні між 3 логотипами зправа інші.

**Comment by Andrukas8** [comment]
додав padding-bottom і трохи збільшив padding-top щоб більш відповідало дизійну

**Comment by bucefal91** [comment]
Закриваю тікет як неактуальний.
