### ISSUE TITLE
Білий фон

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#17]
body section .about-company-wrapper .what-we-do ма білий фон, але білий - це ж дефолт ) Цей білий фон можна сміливо знищувати.

**Comment by bucefal91** [comment]
Проблема ще наблюдається у body section .about-company-wrapper .our-functions

**Comment by Andrukas8** [comment]
виправив. я чомусь не додумався що білий це дефолтне значення, думав що прозоре - дефолтне )

**Comment by bucefal91** [comment]
Закриваю тікет як неактуальний.
