### ISSUE TITLE
Навіщо overflow: auto?

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#19]
А навіщо ти вписав у body section .about-company-wrapper .our-functions .our-functions-row .our-functions-col h4 правило overflow: auto ? це ж здається дефолтне значення?

**Comment by bucefal91** [comment]
ммм, ще не зрозумів чому, але вже бачу для чого)))) Якщо можеш, поясни, будь ласка, як це свойство допомогає у тому, щоб текст не ліз під іконку?

**Comment by Andrukas8** [comment]
здається я про це десь вичитав, що якшо треба завадити тесту обтікати картинку яка має властивість float: left, то допомогти цьому може overflow: auto (тому я і використав його для заголовка і для тексту), але треба це робити обережно, бо можуть з"явитися скроли якщо текту буде забагато,

**Comment by bucefal91** [comment]
Закриваю тікет як неактуальний.
