### ISSUE TITLE
Progress bar width

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#2]
Коли робиш progress bars, то внутрішній фігні, яка показує заповнену частину прогреса, краще давати ширину у відсотках. У тебе є 13% прогресу, то просто впиши ширину у 13%. Бо коли це піде кудись далі, то програмістам значно легше буде вказувати необхідну ширину саме у відсотках, а не перераховувати її з відсотків на конкретні пікселі.

+ ти таким чином маєш додаткову гнучкість - якщо ти завтра цей прогрес бар перенесеш у іншу частину вебсайта і загальна ширина бара збільшиться (наприклад, на новому місці буде більше ширини), то тобі знову ж таки не потрібно буде перераховувати твої пікселі.

**Comment by Andrukas8** [comment]
виправив. css 226

**Comment by bucefal91** [comment]
дякую. Виглядає красивіше, аестичніше і професіональніше при швидкому огляді :) і це добре.
