### ISSUE TITLE
Фон у bell curve

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#20]
А ти випадково не наплутав у фонах для body section .about-company-wrapper .average-economy-wrapper ?

Ти туди вписав градієнт, але потім тут же ще даєш малюнок bell-curve.png. В мене в firefox це не працює. bell-curve.png було би добре  покласти у якийсь інший дочірній дів, щоб менше складнощів було.
![screenshot from 2016-12-22 21-31-59](https://cloud.githubusercontent.com/assets/17630965/21446625/30c14e30-c88e-11e6-976b-920d9294bcb7.png)

**Comment by Andrukas8** [comment]
трошки переробив цю частину сайту. Поперше - подумав, що все- таки кривуля нормального розподілу є частиною контенту, тому додав її як малюнок (бо раніше додавав її як фон одного з дівів). Ще, перерробив фіолетову частину .bell-curve-top

**Comment by bucefal91** [comment]
Закриваю тікет як неактуальний.
