### ISSUE TITLE
Знов ширина вебсайту

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#22]
Ти ще не навчився думати out of the box :) в мене екран більше, ніж твій і майже в кожному дизайні є ця бага
![screenshot from 2017-03-05 17-18-13](https://cloud.githubusercontent.com/assets/17630965/23592514/d5799816-01c7-11e7-8a9a-fa619410dd1f.png)

Бачиш, вебсайт не розтягує свій фон на всю ширину. Зверху то вже хрєн з ним, бо там нам дизайнер намалював лише баннер певної ширини. Але інші полоски сайта мають тягнути свій фон на 100% ширини.

**Comment by Andrukas8** [comment]
наче полагодив.

**Comment by bucefal91** [comment]
Так, пофіксав гарно. Лише логотип і телефон знову трохи "поїхали".
![screenshot from 2017-03-09 23-54-11](https://cloud.githubusercontent.com/assets/17630965/23783804/c7b21d0c-0523-11e7-923a-55093fcaf635.png)

Бачиш, на цьому прінтскріні логотип і телефон йдуть впритик з блакитним банером, а на попередньому прінтскріні у цьому тікеті логотип і телефон мали певний маржин.

**Comment by Andrukas8** [comment]
наче вийшло - помістив логотип і телефон в дів

**Comment by bucefal91** [comment]
Чудово. Тікет зараховано )
