### ISSUE TITLE
Фон у bell curve

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#23]
![screenshot from 2017-03-05 17-20-48](https://cloud.githubusercontent.com/assets/17630965/23592539/4060cc8a-01c8-11e7-83c7-2bb750be490c.png)

Цей фон у дизайні виглядає бірюзовим кольором.

**Comment by Andrukas8** [comment]
зробив

**Comment by bucefal91** [comment]
Дякую. =)
