### ISSUE TITLE
Невистачає текста

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#24]
Ще в середині цього bell curve є текст "72% водителей экономят". В тебе його нема.

**Comment by Andrukas8** [comment]
додав текст. але відчуваю, що там щось не те зі шрифтами. в макеті вони ніби "худіщі"

**Comment by bucefal91** [comment]
В тебе цей текст написано 15px шрифтом, а в дизайні воно написано 14px шрифтом. Це єдина розбіжність, яку я знайшов.

**Comment by Andrukas8** [comment]
так, коли працював над issue #28 - то я це теж полагодив

**Comment by bucefal91** [comment]
Текст є, але він не дуже гарно вирівнян по центру. Ти рішив часний випадок, вписавши правильне значення для left css property.
Є чорна магія. Тобіж це позіціювання по центру можна віришити загальним способом.

Почитай про те, як поставити у центр дів, у якого position: absolute і певна ширина width: 1234px. Але в цьому випадку можна зробити простіше:
text-align:center;
width: 740px (це ширина твого bell curve малюнка)
right: 0; (нехай цей дів починає рендеритись від правого краю свого батька)
профіт.

**Comment by Andrukas8** [comment]
виправив. перейшов від часного до загального.

**Comment by Andrukas8** [comment]
а як оцей?

**Comment by bucefal91** [comment]
так. вигладає добре. Закриваю.
