### ISSUE TITLE
Невистачає рамки

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#25]
![screenshot from 2017-03-05 17-25-37](https://cloud.githubusercontent.com/assets/17630965/23592585/d70a690c-01c8-11e7-91fd-86df3da42d25.png)

У дизайні, там де я підсвітив красним кольором є рамка. В вебсайті її нема :)

Теж сама рамка відсутня у "Показать все сравнения" у наступному блоці. В "Показать все регионы" (блоку, який іде після цих двох).

**Comment by Andrukas8** [comment]
додав рамочки

**Comment by bucefal91** [comment]
Зараховано :)
