### ISSUE TITLE
Соціальні іконки

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#27]
В самому кінці, прямо перед футером, є соціальні кнопки. Вони у вебсайті якось дуже по-спартанськи виглядають - дуже грубо намальований кружок. Колір в дизайні також інший.

Ти їх сам розмалював у блакитний колір? Я в дизайні не знайшов їх ативний стан.

**Comment by Andrukas8** [comment]
Переробив згідно дизайну. То я просто хотів зробити їх трохи цікавшими, але виявилося що відійшов від дизайну.

**Comment by bucefal91** [comment]
Окей. Дякую.
