### ISSUE TITLE
[high priority] Навчитись працювати з шрифтами

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#28]
Все ще є проблеми зі шрифтами. Наприклад, заголовок "Транкила - это удобный сервис по сравнению цен в крупнейших страховых компаниях" не співпадає з дизайном.

У дизайні в нас іде GothamPro Medium 36px, а у вебсайті іде GothamPro Medium **34px** і жирність яка лізить з дефолтних стилів юзер агента.

Далі в дизайні заголовок не просто центрується, а центрується і закривається у максимальну ширину 875px. За рахунок цієї ширини і досягається перенос строки у необхідному місці.

**Comment by bucefal91** [comment]
[28-h2-fix.patch.txt](https://github.com/Andrukas8/responsive_design_practice/files/819877/28-h2-fix.patch.txt)
Ось тобі патч, який фіксає цей заголовок. Порівняй візуально з ним та без нього проти PSD файла.

Далі, продивись усі тексти на баги цього плану (неправильна жирність, розмір шрифта і тд).

**Comment by Andrukas8** [comment]
передивився всі шрифти - в багатьох були розбіжності на 1 піксель, і ще в декількох місцях був використаний неправильний шрифт. Ще таки додивився, що там де логотипи компаній - має бути не слайдер (хоча він і веселіший) а просто круглі логотипчики.

**Comment by bucefal91** [comment]
"Мы поможем Вам найти самое лучшее предложение быстро и бесплатно!" рендериться полужирним через дефолтні шрифти мого firefox. В дизайні він без жирності. Тому треба або замінити h4 тег, або explicitly написати йому нежирність.

**Comment by bucefal91** [comment]
Та сама проблема з "Мы собрали самые частые вопросы для Вашего удобства!"

**Comment by bucefal91** [comment]
Заголовки типу "Какие есть виды КАСКО" (розділ FAQ) неправильно зроблемі візуально (занадто жирні в порівнянні з дизайном) і семантично (ти використовуєш новий font-family - згадай, що я тобі розказував під час нашої останньої бесіди у скайпі).

**Comment by Andrukas8** [comment]
перші два кейса пофіксав. Крайній - "Какие есть виды КАСКО" (розділ FAQ) - тут я видалив font-family: "GothamProBold" і замість нього там де дизайн вимагає font-family: "GothamProBold" використовую font-family: "GothamProMedium" але з додатковим атрибутом font-weight: 700. Хояа навіщо я це зробив- не знаю, бо GothamProMedium наслідується з Body а font-weight: 700 з дефолтних стилів h3.

**Comment by bucefal91** [comment]
Так, "font-family: "GothamProMedium";" треба викинути бо це лише шум. А ось font-weight краще залишити, щоб незалежити від капризів самого браузера.

**Comment by bucefal91** [comment]
Я затупив ? Цей тікет нібито можна закривати чи ще щось у ньому залишилось?

**Comment by Andrukas8** [comment]
думаю можна закривать
