### ISSUE TITLE
Дуже жирна лінія

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#29]
Лінія під "Сравнение ТОП страховых компаний" (і схожих на нього заголовків) дуже жирна (завелика висота). Заміряй правильну висоту з дизайна і зафігач у css, будь ласка.

**Comment by bucefal91** [comment]
Та ж сама проблема є і у футері. Лінія над "© 2016 Транкила Страхование. Все права защищены. Условия использования и Политика конфиденциальности" у вебсайті виглядає жирніше, ніж у дизайні.

**Comment by Andrukas8** [comment]
так, дякую, побачив. Заодно виправив ще кілька таких самих ліній.

**Comment by bucefal91** [comment]
Зараховано)
