### ISSUE TITLE
@font-face

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#3]
Я тобі не хотів ще давати custom fonts, але як ти вже поліз у цю тему, то ось тримай плюшки :)

Ти не зовсім правильно включив твої фонти. Коротка версія: http://stackoverflow.com/a/2436830
Повна версія: https://www.smashingmagazine.com/2013/02/setting-weights-and-styles-at-font-face-declaration/

Раджу прочитати усе ж таки повну, бо там дуже гарно пояснюється смисл behind this specific way.

**Comment by Andrukas8** [comment]
зробив. здається. прочитав обидві версіі, і зрозумів що основна помилка була в тому, що в мене кругом font-weight та font-style були однаковими, а треба щоб вони відповідали фонту.

**Comment by bucefal91** [comment]
Правильно. Треба роздавати правильні font-weights / font-styles для кращої семантики. Але окрім абстрактної симантики тут є справжні практичні наслідки:

- якщо твій фонт за якихось причин не завантажиться, то нехай у "чужому" фонті, але текст відрендириться **жирним** і _курсивом_ у потрібних місцях
- якщо ти завтра надумаєш викинути кастомний шрифт і використати якийсь стандартний, або новий кастом, то тобі буде менше роботи (лише замінити font-family, а жирність і курсивніть придуть "із коробки"
