### ISSUE TITLE
Неправильний фон малюнків

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#30]
Внизу, прямо перед футером є 3 логотипа про сек"юріті. На дизайні вони на білому фоні, а у вебсайті в них сірий фон.
![screenshot from 2017-03-10 00-16-09](https://cloud.githubusercontent.com/assets/17630965/23784338/fa37e09c-0526-11e7-8b2b-2d06b9922348.png)

**Comment by Andrukas8** [comment]
наче виправив

**Comment by bucefal91** [comment]
Зараховано.
