### ISSUE TITLE
Висота форм-елементів не збігає

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#31]
![screenshot from 2017-03-10 00-20-17](https://cloud.githubusercontent.com/assets/17630965/23784424/97efd3c6-0527-11e7-8355-f9d10e91a67f.png)

Ось ця лінія не дотримана.

**Comment by Andrukas8** [comment]
упс, спочатку не ту форму рихтував, але тепер наче ту шо треба вирівняв

**Comment by bucefal91** [comment]
Окей. Зараховано :)
