### ISSUE TITLE
Не вистачає рамки

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#32]
Дивись у скріншоті пункт №1.

**Comment by bucefal91** [comment]
![screenshot from 2017-03-10 00-22-59](https://cloud.githubusercontent.com/assets/17630965/23784497/f5a07516-0527-11e7-9e2c-ba871b78311f.png)
Ось скріншот :)

**Comment by bucefal91** [comment]
Пункт №2 - false alarm :)

**Comment by Andrukas8** [comment]
полагодив. я додивився - там навіть і в пункті 2 теж є нижній бордер, і навіть у випадаючої відповіді теж

**Comment by bucefal91** [comment]
Окей.
