### ISSUE TITLE
Відкрите/закрите питання 

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#33]
Знак питання змінює свій стан в залежності від того чи є відкритим його питання. Відкриті питання мають знак питання більш чорний.

**Comment by Andrukas8** [comment]
ага, так, побачив. Тільки - я зрозумів з дизайну, що знак питання змінюється в залежності від того чи зараз курсор миші знаходиться над самим питанням (бо те питання, щр відкрите теж має сірий знак питання, а темніший знак питання там, де показане синьє пунктирне підкреслення), тому так і зробив, але може я не правий. Ще - думав як зробити transition ефект для знака питання так, щоб не було ефекту виїжджання, але це ускладнюється тим, що hover на один елемент, а зміни відбуваються з іншим, тому transition не робив.

**Comment by bucefal91** [comment]
аааааа. Я зрозумів твою точку зору. Добре, хай буде так.

Я не дуже зрозумів який саме ефект віїжджання ти маєш на увазі. Якщо є бажання, то напиши трохи детальніше і я спробую порадити щось. Я просто не зрозумів твою думку.

**Comment by Andrukas8** [comment]
виходить так, що в мене оби два знаки питання (темніший і світліший) знаходяться в спрайті, тому коли я роблю transition на ховері - то ефект виходить що один знак питання виїжджає на інший, щоб його замінити. Доцільним ефектом булоби помірна заміна одного знака питання на інший (типу fade in fade out). В інтереті є розв'язання цієї проблеми для того випадку, коли hover робиться на саму картинку (там суть в тому що додається картинка повністю прозора, і потім transition ефект "анімує" opacity). Але в даному випадку - це ускладюється тим, що hover іде на лінк а ефект має бути на знак питання.

**Comment by Andrukas8** [comment]
ось закомітив що в мене вийшло. Виходячи з цієї статті - в мене класичний Failing Example:
https://gordonlesti.com/css-background-transitions-with-image-sprites/

**Comment by Andrukas8** [comment]
перечитав статтю ще раз... поесперементував для нашого випадку - виявилося не все так складно :) закомітив рішення

**Comment by bucefal91** [comment]
Виглядає добре рішення. Єдине, якщо би ти поклав span всередину h3 тега, то твій CSS селектор був би простіше -  body section .faq-wrapper .faq-container .faq-item .faq-heading h3:hover .question-mark::after

Якщо я тебе правильно зрозумів, то ця частина (селектор) в тебе викликала певні труднощі.

Ще питання, ти зробив transition in .5s і transition out .2s. Це запланований пыщь-эффект або це баг?)

**Comment by Andrukas8** [comment]
то був баг: я не встигав роздивитись ефект при 0.2s, тому збільгив його до 0.5s, а потім забув повернути назад

**Comment by bucefal91** [comment]
окей. Закриваємо тоді.
