### ISSUE TITLE
"Сравнить цены" :active

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#35]
Для кнопки "Сравнить цены" можна зробити :active стан, де вона буде виглядати справді ніби на неї натиснули. UX рулить :)

Tip: можна просто сховати border-bottom і тоді вона буде відчуватись ніби на неї натиснули.

**Comment by Andrukas8** [comment]
Зробив, дякую за пораду. Ще додав ux до кнопки знизу, але оскільки у цієї кнопки нема бордера - то зробив зміну opacity для неї. Хоча я би перебалакав з дизайнером, і запропонував би уніфікувати кнопки - щоб мали однаковий ux.

**Comment by bucefal91** [comment]
Дуже добре, правильно мислиш :)
