### ISSUE TITLE
Очіпятка

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#36]
<a class="call-agent small-mobile-show" hreg="#">Вызвать Агента</a>

Треба href, a не hreg.

**Comment by bucefal91** [comment]
ммм. не вставився html код.

`<a class="call-agent small-mobile-show" hreg="#">Вызвать Агента</a>`

**Comment by bucefal91** [comment]
Ось ще одна

`<div clas="slider-arrow">`

**Comment by Andrukas8** [comment]
дякую, виправив
