### ISSUE TITLE
Трохи м"яса

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#38]
Ось, м"ясо привезли)))
![screenshot from 2017-03-11 23-39-10](https://cloud.githubusercontent.com/assets/17630965/23829305/b37552ae-06b4-11e7-9bd0-125e4f89bd23.png)

Пункт 1: Треба вертикально відцентрувати
Пункт 2: Воно ж блакитне у дизайні :)
Пункт 3: "в год" у тебе написано жирним, а в дизайні воно нежирне.
Пункт 4: Хрєнь (палочки) треба відцентрувати вертикально зі словами "точность цены" і "хорошая"
Пукнт 5: В дизайні обидва свова "точность цены" і "хорошая" написані однаковим шрифтом у однаковому розмірі. А у тебе в дизайні розмір явно різний.

Качай левел на пошук цих розбіжностей. Це як у дитинстві були 2 схожі малюнки і "знайди 10 незбіжностей". Я тобі хочу показати рівень схожості між дизайном і твоїм кінцевим продуктом (вебсайтом), який очікується від нормального верстальщика. І це ще не pixel-perfect левел. Це просто візуальна збіжність.

**Comment by Andrukas8** [comment]
дякую! хоча я вегетаріанець )))) але наче пофіксав

**Comment by bucefal91** [comment]
1й пункт все ще вимагає трохи роботи. Може у твоєму браузері воно краще виглядає, але в мене й досі невідцентровано по вертикалі.
![screenshot from 2017-03-15 22-39-01](https://cloud.githubusercontent.com/assets/17630965/23982029/598e1c02-09d0-11e7-8b89-b1eb1ba5f3c7.png)

**Comment by Andrukas8** [comment]
вирівняв

**Comment by bucefal91** [comment]
Чудно. Зараховано. Я просто ще додам, що я часто вирівнюю вертикально текст, який ніколи не буде йти на 2гу строку наступним чином:
height: 50px;
line-height: 50px;

Тобіж якщо дати однакову висоту і line-height, то сам текст встане саме по центру по вертикалі у ціх 50 пікселях.
