### ISSUE TITLE
Горизонтальне центрування

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#39]
![screenshot from 2017-03-11 23-52-14](https://cloud.githubusercontent.com/assets/17630965/23829413/17619e3e-06b6-11e7-9fe7-1050fa719c8e.png)

Цей текст треба вирівняти горизонтально по центру.

**Comment by Andrukas8** [comment]
відцентрував

**Comment by bucefal91** [comment]
Перфекто =)
