### ISSUE TITLE
Знову відступити і лєсєнка

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#4]
В тебе в ЦСС в деяких місцях 4 пробєла використовується, а в інших 2. І ще є пару місць, де видно, що код форматувався "руками", а не роботом, який усе під 1 формат робить.

Навчись одразу робити impeccable форматування кода. Це дуже гарний навичок, який додає візуального професіоналізма у твою роботу. У форматування кода є лише 1 критерій якості: однорідність - увесь CSS має бути відформатований в одному форматі (і те ж саме про HTML & JavaScript, лише що кожен з цих 3 груп може мати свій власний формат, але всередині групи формат має бути 100% однаковим).

Ще одна дуже корисна порада: роби коміти у репозитарій лише на стабільних етапах. Під стабільністю я тут маю на увазі як стабільність коду, так і стабільність його форматування. Тобто, ти у себе в working copy можеш робити будь-які оргії з кодом, але історія твоїх комітів має бути "красивою". Не знаю, чи мені вдалося передати тут мою думку, але вже інтерпретуй це як забажаєш )))

**Comment by Andrukas8** [comment]
відступи виправив. про стабільність зрозумів )))
