### ISSUE TITLE
2 рази border

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#40]
header .header-container .header-content-wrapper .header-data-wrapper .start-selection-wrapper .start-selection-select {
  width: 90%;
  border-radius: 5px;
  margin-top: 25px;
  border: 0;
  background-color: white;
  background-image: url('pics/dropdown-arrow-big.png');
  background-repeat: no-repeat;
  background-position: 98% 50%;
  padding: 16px 8.43% 16px 4.2%;
  cursor: pointer;
  font-size: 18px;
  border: 2px solid rgb(221, 221, 221);
  height: 60px;
}
Тут 2 рази декларується border. Подумай про PHP storm. Він усі ці речі тобі підсвічує. В тебе дуже багато помилок цього типу.

**Comment by Andrukas8** [comment]
поставив css-лінтер, ось його онлайн версія (http://csslint.net/). Видав мені 95 "покращень", серед яких були і подвійні декларування. Вивчив багато цікавого - наприклад про fallback color коли використовується rgba. Але додатково - йому не подобається що багато разів використовується h2, хоче викинути star-selector і не розуміє спрайтів...

**Comment by bucefal91** [comment]
Я їм ніколи не користувався, але я щаслив))) видно, що він тебе вишкаляв. Я від себе хочу лише додати перевірку на наявність EOL символа в кінці файла. У юніксах зазвичай усі текстові файли мають закінчуватись порожньою строкою. І ти саме у комміті до цього тікета видалив цей перенос строки. Це не потрібно виправляти, але якщо твій css linter можна кастомізувати, то я би втулив у нього цю перевірку.
