### ISSUE TITLE
Неточне форматування тексту

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#41]
Заголовок "Мы помогли более 4 миллионам водителей сэкономить в среднем около 19 298 рублей в год на покупке полиса КАСКО" має інші переноси строк у дизайні. Те саме відбувається і з самим текстом під заголовком.

Ти там поставив 60% ширини, але краще поставити конкретний розмір у пікселях так, щоб текст переносився саме як у дизайні.

**Comment by Andrukas8** [comment]
Заголовок виправив, але той текст що нижче - ніяк 100% не вирівнєються - то там то там слово вилазить

**Comment by bucefal91** [comment]
Ну і х*й с нім) Зараховано.
