### ISSUE TITLE
Логотипи Топ 20 страхувальників

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#42]
Щось логотипи погано виглядають. 
![screenshot from 2017-03-19 18-12-03](https://cloud.githubusercontent.com/assets/17630965/24086144/9851e8b8-0ccf-11e7-8c2f-196add867708.png)

В мене тут 3 зауваження:

1. (цей пункт можна не фіксать) Я би їх не фоном поклав, а <img /> тегами, бо я їх більши сприймаю як частину контента і не як частину дизайна (look & feel).
2. Вони виглядають погано видно лише частину самого логитипу
3. В дизайні вони біль сіріші чи полупрозорі ніж у вебсайті.

**Comment by Andrukas8** [comment]
зробив як у дизайні. Пункт 1 пофіктав теж. Щодо пункту 2 - то в дизайні логотипи видно лише частково, тому я повирізав їх як є.

**Comment by bucefal91** [comment]
Ок. Дякую. Усе чудово. Закриваємо тікет.
