### ISSUE TITLE
Х"юстон, у нас проблеми з футером

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#43]
2 проблеми з футером. Дивись у прінтскріні.
![screenshot from 2017-03-19 18-17-25](https://cloud.githubusercontent.com/assets/17630965/24086184/8bb8d2fa-0cd0-11e7-83be-3e4ea07a56e2.png)

**Comment by Andrukas8** [comment]
полагодив. Ще - трошки підігнав відстані між рядками у футері.

**Comment by bucefal91** [comment]
Окей. Дякую.
