### ISSUE TITLE
Останній ривок

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#44]
Є невелика проблема зі "стиковкою" хедера і основного тіла вебсайта. Там десь 2-3 пікслі роз"їхались.

Дивись у скріншоті.
![screenshot from 2017-03-22 23-40-57](https://cloud.githubusercontent.com/assets/17630965/24233678/5f6be5bc-0f59-11e7-9cce-a1dc290604d8.png)

**Comment by Andrukas8** [comment]
нібито полагодив, але чомусь є відчуття, що халтура...

**Comment by bucefal91** [comment]
Візуально воно виглядає добре. Мені не дуже сподобався негативний margin-top у header .header-container .header-content-wrapper .header-data-wrapper

По ідєї тобі достатньо було зменишити відступ між "Сравните ценны мгновенно!" і цією хрєнью. І тоді зникла б необхідність у цій негативній маржі.

В загалі тобі буде весело темізувату цу частину у responsive :) Там дуже багато речей виглядають заплутаними. Але саме для цього ми і робимо це завдання - щоб на практиці бачати та "відчути" ці речі.

**Comment by bucefal91** [comment]
Ну але я все одно закриваю тікет, бо задача виконана.
