### ISSUE TITLE
Опять бага у хедері

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#45]
![screenshot from 2017-04-17 22-47-09](https://cloud.githubusercontent.com/assets/17630965/25113886/3c83c95e-23c0-11e7-83be-83715445b019.png)
Знову лого і № телефона "поїхали" за банер у хедері. ;)

**Comment by Andrukas8** [comment]
зробив. як я раніше цього не побачив - очевидна ж штука)))

**Comment by bucefal91** [comment]
Зараховано)
