### ISSUE TITLE
Щось не те з графікою

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#46]
Цей пункт я, здається, прогледів коли ми ще на desktop-only працювали.

4 іконки у розділі "Транкила - это удобный сервис по сравнению цен в крупнейших страховых компаниях" виглядають не так, як у дизайні.

Ось ці іконки.
![screenshot from 2017-04-17 22-56-02](https://cloud.githubusercontent.com/assets/17630965/25114027/2322ed86-23c1-11e7-9ee1-e462cc5cb546.png)
У дизайні що у desktop, що у 980px розмірах є наступні розбіги:

- У хрюшки в дизайні лінії сірі, а у вебсайті чорні
- У "бережем время" трикутник у дизайні блакитний, а в дизайні чорний
- У "найдем нужную страховку" знову лінії сірі, а у вебсайті чорні.

**Comment by Andrukas8** [comment]
виправив - вирізав з дизайну по новому і вставив в спрайт

**Comment by bucefal91** [comment]
Дуже добре. То мабудь твій gimp фінти робив. Не думаю, що ти навмисно ночами домальовував графіку =)
