### ISSUE TITLE
FAQ відповідь

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#47]
У відповіді на FAQ відступи між параграфами завеликі.
![screenshot from 2017-04-17 23-02-08](https://cloud.githubusercontent.com/assets/17630965/25114134/fd3d41a6-23c1-11e7-8231-a0fda9179071.png)

**Comment by Andrukas8** [comment]
зробив.

**Comment by bucefal91** [comment]
Дякую.
