### ISSUE TITLE
980px у футері невистачає простіру

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#48]
На 980 пікселях у футера зникає відступ з низу. Порівняй з дизайном, він там є.
![screenshot from 2017-04-17 23-05-01](https://cloud.githubusercontent.com/assets/17630965/25114217/a2fb509c-23c2-11e7-8e68-3085fc8ea2f0.png)

**Comment by Andrukas8** [comment]
зробив. заодно ще і ширину настроїв, щоб перенос слів був правильний. Потім подивився щоб це не пошкодило дрібніші медіакверіс - і воно таки пошкодило, тоді залатав ширину ще раз на рівні 768px

**Comment by bucefal91** [comment]
Дуже добре.
