### ISSUE TITLE
768px відступ "Посмотрите сколько Вы можете сэкономить на КАСКО"

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#49]
На дизайні цей відступ менше.
![screenshot from 2017-04-17 23-08-54](https://cloud.githubusercontent.com/assets/17630965/25114270/2737ac7a-23c3-11e7-9a66-f82f242723e7.png)

**Comment by Andrukas8** [comment]
наче зробив. ще, відцентрував правильно заголовок

**Comment by Andrukas8** [comment]
упс - закомітив не правильну назву... - це для #50

**Comment by bucefal91** [comment]
Окей.
