### ISSUE TITLE
to Alex: Positioning

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#5]
Багато хімічив з розташуванням сірої форми з синьою кнопкою. Не впевнений що там все правильно.

**Comment by bucefal91** [comment]
Я подивився, ти там насправді до дуже чорної магії звернувся. Абсолютне позіціонювання там зайве.

![screenshot from 2016-12-11 21-55-36](https://cloud.githubusercontent.com/assets/17630965/21087600/f0568828-bfec-11e6-8d03-5968ffafcbc2.png)

Я би це зробив наступним чином:

- є контейнер, у якому будуть знаходитись 3 дитини (ці 3 колонки). У контейнера не включаєш clearfix, а просто пишеш потрібну висоту
- усім дітям даєш float
- останню дитину трохи "підгоняєш" до правильних розмірів та позціонювання за допомогою margin-top: -100px і height: 600px

Не скажу, що це ідеальне рішення, але це те, що мені прийшло в голову за 15 хвилин :)

**Comment by Andrukas8** [comment]
Зробив, наче вийшло.

**Comment by bucefal91** [comment]
Закриваю тікет як неактуальний.
