### ISSUE TITLE
768px footer

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#50]
теж трохи не такі відступи у футері, як на дизайні.
![screenshot from 2017-04-17 23-11-50](https://cloud.githubusercontent.com/assets/17630965/25114319/7f589b44-23c3-11e7-898f-9bf5666b195c.png)

**Comment by Andrukas8** [comment]
додав додаткові корективи.

**Comment by bucefal91** [comment]
Дякую.
