### ISSUE TITLE
480px вызвать агента - ахутнг

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#51]
Може не червоний, а якийсь більш нейтральній колір впилити?)
![screenshot from 2017-04-17 23-14-23](https://cloud.githubusercontent.com/assets/17630965/25114375/eb6f1812-23c3-11e7-8172-b4e925929413.png)

**Comment by Andrukas8** [comment]
Поправив. Щоб було красіво - взяв пепеткою колор з background image, (вибрав трохи темніший)

**Comment by Andrukas8** [comment]
:)
https://www.youtube.com/watch?v=79tyzO2Qvyg

**Comment by bucefal91** [comment]
Окей. Зараховано.)
