### ISSUE TITLE
480px відступи для заголовка

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#52]
У дизайні ці 2 відступи (зверху і знизу) однакові.
![screenshot from 2017-04-17 23-17-09](https://cloud.githubusercontent.com/assets/17630965/25114420/407032b0-23c4-11e7-9c99-68ac315d2b8d.png)

**Comment by Andrukas8** [comment]
виправив

**Comment by bucefal91** [comment]
Дякую.
