### ISSUE TITLE
480px простір від іконки Бережем время

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#53]
Іконка для пункту "бережем время" виглядає трохи "відірваною" від свого пункта, бо в неї завеликий відступ знизу. У дизайні він менше.
![screenshot from 2017-04-17 23-19-53](https://cloud.githubusercontent.com/assets/17630965/25114492/a8a0d434-23c4-11e7-8948-5abb5849cedb.png)

**Comment by Andrukas8** [comment]
зробив

**Comment by bucefal91** [comment]
Дякую.
