### ISSUE TITLE
Іконки і свістюльки у тектових полях

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#56]
Я ось щойно на роботі схоже питання рішав - диви зліва у paid membership redeem coupon - http://irt.dev.ws.agency/user/register

Тобто в тебе є UX задача - втюлити якусь свістульку/іконку у текстове поле. Є проблема, т.к. <input /> не має дітей, то ти не можеш це зробити через ::after псевдоселектор.

В тебе така сама задача стоїть з іконкою календаря.
![screenshot from 2017-04-18 23-36-27](https://cloud.githubusercontent.com/assets/17630965/25163485/62c2e926-2490-11e7-939b-a39d175af65f.png)

Ти зробив досить гарне рішення, але є 2 проблеми:
- ти не зміг заюзати спрайт. Тут ти нічого концептуально не можеш зробити, бо треба класти фоном на теоретично безмежне текстове поле.
- коли пишеш текст, то він залазить на твою іконку (диви мій прінтскрін вище) і виходить погано. Ця хрєнь рішається дуже просто - треба хєрануть padding-right: 50px і буде все добре)

А ось щодо 1го пункту, то я у себе на работі зробив наступне. Маємо
<div class="input-wrapper"><input type="text" /></div>
І тоді ми робимо:
.input-wrapper {
  position: relative;
}
.input-wrapper::after {
  content: "";
  position: absolute;
  top: 5px;
  right: 5px;
  width: 10px;
  height: 10px;
  background: url(my-sprite.png) -50px 0 no-repeat;
}
.input-wrapper input {
  padding-right: 50px;
}
Бачиш трюк?

**Comment by Andrukas8** [comment]
це просто геніально! я скільки шукав - ніде не міг знайти схожого вирішення. Круто!

**Comment by bucefal91** [comment]
От і добре.
