### ISSUE TITLE
:nth-child(1) === :first

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#57]
Я в тебе в ЦСС бачу :nth-child(1), але це рівносильно :first псевдоселектору. Обидва валідні і обидва можна використовувати. Просто :first було придумано як short cut.

Я нічого не спонукаю правити. Просто хотів заострити твою увагу на цьому пункті, бо я подумав, що можливо ти цього не знаєш.

**Comment by bucefal91** [comment]
пердон))) це ж :first-child ))) а не просто :first

**Comment by Andrukas8** [comment]
так, то я для різноманітності -  :first-child вже використовував, тому спробував щось не таке мейн-стрімне :)

**Comment by bucefal91** [comment]
Окей. Хай буде тоді.
