### ISSUE TITLE
теоретично-філософський тікет

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#58]
А тобі не складно було так організувати твій ЦСС? Ти його зкомпонував по media queries. Я завжди компоную по компонентам (вибачай за каламбур) - тобто хедер іде поряд з хедером, "ось цей блакитний блок" описується цілком в одному місці ЦСС файла.

А в тебе навпаки: отут іде desktop, отут іде tablet і тд. Тому виходить, що хедер є десь з 100 строки по 300 і потім ще раз "нагоняється" по таблетам десь в районі 1100 строки.

Я не кажу, що так не можна робити. Я просто зі свого досвіду знаю, що для мого мозока такий метод організації не буде оптимальним. Тому щиро запитую, чи тобі було зручно?

Ось мій перший responsive CSS код (і я його також робив без будь-якого фреймворку) http://takearest.ru/sites/all/themes/basic/css/style.css

Ще я також свій перший спрайт зробив як ти))) - http://cdn1.takearest.ru/sites/all/themes/basic/images/sprite.png
Але розумні хлопці радять усе ж таки не робити з цього таємного мистецва, а брати певну методологію собі на поміч. Наприклад ось такий набір правил:
- спрайт буде вертикальний (тобто кожен наступний малюнок всередині спрайта завжди буде іти під попередній малюнок... це буде таке собі полотно, але х коордіната завжди буде 0 і це зручно)
- брати за основу сітку з кроком у 10 пікселів (правильне число вписати, але 10 - це reasonable default). Тобто, якщо рисунок N - 1 закінчився на 502 пікселі по висоті, то рисунок N починатиметься з 510 пікселя по висоті. Так також зручніше, бо в тебе y координата завжди буде кратна 10.

**Comment by Andrukas8** [comment]
дякую, ідею я зрозумів. Спрайт наступного разу організую вертикальним. А про CSS навіть не знаю, наче зручно - бо я уявляю так: основний CSS і потім пішли модифікації для різних екранів. Тобто коли працюю над дизайном меншого екрану - то всі зміни в дизайні мені зручніше мати в одному місці. Але, може треба буде спробувати в майбутньому зробити по іншому.

**Comment by bucefal91** [comment]
Окей. Зрозуміло.
