### ISSUE TITLE
Transition between Desktop & Tablet

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#59]
Коли ми по ширині вже менше desktop, але ще не доїхали до tablet (980px), з"являється горизонтальний скролл.

Треба зробити так, щоб його не було. Тобто зазвичай нам дизайнер дає 3-4 розміри, але ми вже самі маємо додумати усе, що іде між цими 3 конкретними розмірами так, щоб не було горизонтального скроллу і UX був на висоті.

Атачу трохи скріншотів.
![screenshot from 2017-04-19 00-14-11](https://cloud.githubusercontent.com/assets/17630965/25164257/71533e00-2495-11e7-9171-45f8a3504cb0.png)
![screenshot from 2017-04-19 00-14-17](https://cloud.githubusercontent.com/assets/17630965/25164258/71555258-2495-11e7-9b8c-6b4d09a97e77.png)

**Comment by Andrukas8** [comment]
проблему зі скролем ідентифікував - він з'являється через те, що у формточки "Давайте Начнем" margin-left був вказаний в абсолютній величині - 750 пікселів. Тому, коли змінювався розмір вікна - ці 750 пікселів не змінювалися а так і лишалися. Як варіант вирішення - я замінив 750пікселів на "margin-left: 56.5%;". Стролл зник. Але - при зменшенні масштабу - формочка улітає далеко за межі сайту, А при зміні розміру вікна - замість скролу видно ось що:
![image](https://cloud.githubusercontent.com/assets/21954163/26485007/cfecd8a6-41fd-11e7-892d-a7d37b68ee5f.png)

намагався використати замість margin-left різні right, left, від'ємні значення, покищо нічого не вийло, буду далі думать

**Comment by Andrukas8** [comment]
виправив цю помилку - виявляється "абсолютній дитині" не вистачало "відносного батька"

**Comment by bucefal91** [comment]
Щось ця частина і досі виглядає не дуже: https://cloud.githubusercontent.com/assets/17630965/25164258/71555258-2495-11e7-9b8c-6b4d09a97e77.png

Але я пропоную сказати "хрєн з ним". Його там все рівно толком не втулити. Єдине, що там твоя комбінація з width: 100%; max-width: ___px; margin-right: -10%; виглядає трохи паливно. Але я пропоную закрити цей тікет так, як воно є зараз.

**Comment by Andrukas8** [comment]
згоден

**Comment by bucefal91** [comment]
окей. тут здається пани вирішили закривати тікет, то я його закриваю.
