### ISSUE TITLE
Читать полностью - по центру і блакитним

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#61]
В дизайні цей лінк виглядає інакше.
![screenshot from 2017-07-11 13-12-00](https://user-images.githubusercontent.com/17630965/28083394-c97651da-663a-11e7-9266-d1893e1671b2.png)

**Comment by Andrukas8** [comment]
зробив. Стилі для цього лінка втулив не туди куди треба було

**Comment by bucefal91** [comment]
Окей, чудненько. дякую.
