### ISSUE TITLE
Знову горізонтальний скролл

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#62]
В мене знову з"явився горізонтальний скролл. Дивись прінт скрін.
![screenshot from 2017-07-11 13-14-09](https://user-images.githubusercontent.com/17630965/28083494-2514b522-663b-11e7-94e2-978cc363a57d.png)

**Comment by Andrukas8** [comment]
хм... перевірив у в Хромі, Опері, ІЕ, Firefox в різних зумах - горизонтального скрола не помітив.
Глянь будь-ласка в себе ще раз - може бути 10 варіанти:
01 якимсь чином працюючи над попередніми тікетами скрол зник сам
10 версії моїх браузерів не співпадають з версіями твоїх браузерів

**Comment by bucefal91** [comment]
Скролл зник у мене також. Окей, тоді закриваємо тікет.
