### ISSUE TITLE
Х"юстон, у нас проблеми з футером

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#64]
У футері чомусь майже повний екран білого порожнього сайту на маленький ширині.
Атачу прінтскрін.
![screenshot from 2017-07-11 13-20-40](https://user-images.githubusercontent.com/17630965/28083749-0e596e44-663c-11e7-9ad5-8db0b17088b4.png)

**Comment by Andrukas8** [comment]
Екіпаж Апоkло, Х'юстон проблеми не бачить, телеметрія нормі:
![image](https://user-images.githubusercontent.com/21954163/28199752-c1ba0c88-6870-11e7-854d-93ec7516c235.png)

**Comment by bucefal91** [comment]
Roger that. В мене ця бага зникла.
