### ISSUE TITLE
input type="select"

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#7]
В тебе в хтмл коді є 

`<input class="question-form-input calendar-field" type="select" placeholder="день рождения">`

це треба переробити у type="text" або `<select>...</select> 
`
:)

**Comment by Andrukas8** [comment]
Поміняв type="select" на type="text" на даному елементі і на іншому, який теж пов"язаний з датою - "начало стажа". Проте, може там де "начало стажа" там дизайнер мав на увазі просто рік початку... але менше з тим =)

**Comment by bucefal91** [comment]
Добре.
