### ISSUE TITLE
CSS padding

### ISSUE THREAD

**Issue by bucefal91** [Andrukas8/responsive_design_practice#9]
```
header .header-content-wrapper .header-data-wrapper .form-wrapper .question-form .calendar-field {
  background-image: url('pics/calendar.png');
  background-repeat: no-repeat;
  background-position: 98% 50%;
  padding-right: 35px;
  padding: 9px 5px;
}
```
В цьому сніпеті padding-right тут же перезаписується директивою padding. Тобто padding-right не дає ніякого ефекту і просто займає одну додаткову строчку кода, яка нічого продуктивного не робить.

Там ще в іншому місці є така сама ситуація з padding-right, який одразу перезаписується padding'ом.

**Comment by Andrukas8** [comment]
виправив

**Comment by bucefal91** [comment]
чудово!
